### PR TITLE
Fault injector

### PR DESCRIPTION
**Pull request by danielstumpp**
Fault injector for testing reliability techniques. Highlights below, see README for more details.

### Summary of Changes
- Fault injector for testing
- three modes of operation
  - single error injection
  - double error injection
  - probabilistic error injection
- accepts Mat CV_32F type and most standard C++ types (int, float, double, uint8_t, etc...)

### CODE REVIEW

**Comment by rom81** [comment]
I still need to review and test this more thoroughly but some initial thoughts:

1. We should probably change the random number generator seed to be constant (not dependent on current time) since we want to be able to perform the same 'random' fault injection multiple times for testing. 
2. I don't understand why we'd want to enable/disable the fault injector -- I don't see any issue with doing it, but I'm not sure why we'd want to. Can you clarify why you included that?

**Comment by danielstumpp** [comment]
> 1. We should probably change the random number generator seed to be constant (not dependent on current time) since we want to be able to perform the same 'random' fault injection multiple times for testing

I thought we were planning to use a random probability model over many runs. I think this will give us a better holistic understanding of how well it responds to errors. If we only pick certain seeds we could inadvertently bias the injections towards one type/area that helps one technique over the others. 

We can add a method to re-seed the rng so that a static seed can be used if that is needed for specific cases but I think a high number of injection iterations with random injections will give us better results. Assuming we run enough iterations

**Comment by danielstumpp** [comment]
> 2\. I don't understand why we'd want to enable/disable the fault injector -- I don't see any issue with doing it, but I'm not sure why we'd want to. Can you clarify why you included that?

Yeah, `enable()` and `disable()` don't actually do anything. I had them when I initially sketched out the class but I'm not sure they are required

**Comment by rom81** [comment]
I see what you mean with 2). I was envisioning running the same seed for a set of runs, e.g. a baseline run with some seed0, then an ABFT run with some seed0, then another baseline run with some seed1, then an ABFT run with some seed1 and so on -- the idea being that we can see how the baseline compares to the ABFT run given the same faults. 

But I agree that this can probably be solved by just performing some large number of runs with random seeding.

**Comment by rom81** [comment]
Also, as is, there's a typo on line 35 when you try to build -- I'll go ahead and fix it.

**Comment by rom81** [comment]
I just did some light testing and this seems like it works to me -- my only suggested change is that it seems like it might be better to just have the inject() methods be static so we don't need to call them with a fault injector object, but that's a small thing.

**Pull request merged**
